src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UsuarioRepository::class)
 * @ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(columns={"email", "username"})})
 * @UniqueEntity(fields={"email"}, message="El correo introducido ya existe")
 */

class Usuario implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
    * @ORM\Column(type="boolean")
    */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="debes proporcionar un correo para registrarte")
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Rellena el campo de password")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="indica tu nombre")
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="indica tus apellidos")
     */
    private $apellidos;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha_alta;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $direccion;


    public function __construct()
    {
        $this->fecha_alta = new DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getFechaAlta(): ?\DateTimeInterface
    {
        return $this->fecha_alta;
    }

    public function setFechaAlta(?\DateTimeInterface $fecha_alta): self
    {
        $this->fecha_alta = $fecha_alta;

        return $this;
    }

    public function getTelefono(): ?int
    {
        return $this->telefono;
    }

    public function setTelefono(?int $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(?string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    /**
     * @see UserInterface
     * @return array
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array $roles
     * @return $this
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {
        return $this->username;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

}

src/Form/UsuarioType.php
<?php

namespace App\Form;

use App\Entity\Usuario;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;

class UsuarioType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class)
            ->add('password', PasswordType::class)
            ->add('username', TextType::class)
            ->add('apellidos', TextType::class)
            ->add('telefono', TextType::class)
            ->add('direccion', TextType::class)
            ->add('agreeTerms', CheckboxType::class, [
                'mapped' => false,
                'constraints' => [
                    new IsTrue([
                        'message' => 'You should agree to our terms.',
                    ]),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Usuario::class,
        ]);
    }
}

src/Controller/UsuarioController.php
<?php

namespace App\Controller;

use App\Entity\Usuario;
use App\Form\UsuarioType;
use App\Repository\UsuarioRepository;
use App\Security\EmailVerifier;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mime\Address;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;

#[Route('/usuario')]
class UsuarioController extends AbstractController
{

    private EmailVerifier $emailVerifier;

    /**
     * @param EmailVerifier $emailVerifier
     */
    public function __construct(EmailVerifier $emailVerifier)
    {
        $this->emailVerifier = $emailVerifier;
    }


    #[Route('/', name: 'usuario_index', methods: ['GET'])]
    public function index(UsuarioRepository $usuarioRepository): Response
    {
        return $this->render('usuario/index.html.twig', [
            'usuarios' => $usuarioRepository->findAll(),
        ]);
    }

    #[Route('/register', name: 'usuario_register', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $usuario = new Usuario();
        $form = $this->createForm(UsuarioType::class, $usuario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $hashedPassword = $passwordHasher->hashPassword(
                $usuario,
                $usuario->getPassword()
            );
            $usuario->setPassword($hashedPassword);

            $usuario->setRoles(["ROLE_USER"]);

            $entityManager->persist($usuario);
            $entityManager->flush();

            $this->emailVerifier->sendEmailConfirmation('app_verify_email', $usuario,
                (new TemplatedEmail())
                    ->from(new Address('proyectoDeClase7777@gmail.com', 'Ayoub Hiar'))
                    ->to($usuario->getEmail())
                    ->subject('Please Confirm your Email')
                    ->htmlTemplate('registration/confirmation_email.html.twig')
            );

            return $this->redirectToRoute('index_page', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('usuario/new.html.twig', [
            'usuario' => $usuario,
            'form' => $form,
        ]);
    }

    /**
     *     * @Route("/verify/email", name="app_verify_email")
     *      */
    public function verifyUserEmail(Request $request, UsuarioRepository $usuarioRepository): Response
    {
        $id = $request->get('id');

        if (null === $id) {
            return $this->redirectToRoute('login_page');
        }

        $user = $usuarioRepository->find($id);

        if (null === $user) {
            return $this->redirectToRoute('login_page');
        }

        // validate email confirmation link, sets User::isVerified=true and persists
        try {
            $this->emailVerifier->handleEmailConfirmation($request, $user);
        } catch (VerifyEmailExceptionInterface $exception) {
            $this->addFlash('verify_email_error', $exception->getReason());

            return $this->redirectToRoute('login_page');
        }

        // @TODO Change the redirect on success and handle or remove the flash message in your templates
        $this->addFlash('success', 'Tu correo electrónico ha sido verificado correctamente.');

        return $this->redirectToRoute('login_page');
    }


    #[Route('/{id}', name: 'usuario_show', methods: ['GET'])]
    public function show(Usuario $usuario): Response
    {
        return $this->render('usuario/show.html.twig', [
            'usuario' => $usuario,
        ]);
    }

    #[Route('/{id}/edit', name: 'usuario_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Usuario $usuario, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UsuarioType::class, $usuario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('usuario_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('usuario/edit.html.twig', [
            'usuario' => $usuario,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'usuario_delete', methods: ['POST'])]
    public function delete(Request $request, Usuario $usuario, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$usuario->getId(), $request->request->get('_token'))) {
            $entityManager->remove($usuario);
            $entityManager->flush();
        }

        return $this->redirectToRoute('usuario_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/usuario/_delete_form.html.twig
<form method="post" action="{{ path('usuario_delete', {'id': usuario.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usuario.id) }}">
    <button class="btn">Delete</button>
</form>

templates/usuario/_form.html.twig
{{ form_start(form) }}

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="email">email</label>
        {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder':'email'}}) }}
        {{ form_errors(form.email) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="password">password</label>
        {{ form_widget(form.password, {'attr': {'class': 'form-control', 'placeholder':'password'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="username">nombre</label>
        {{ form_widget(form.username, {'attr': {'class': 'form-control', 'placeholder':'nombre'}}) }}
        {{ form_errors(form.username) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="apellidos">apellidos</label>
        {{ form_widget(form.apellidos, {'attr': {'class': 'form-control', 'placeholder':'apellidos'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="telefono">telefono</label>
        {{ form_widget(form.telefono, {'attr': {'class': 'form-control', 'placeholder':'telefono'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="direccion">direccion</label>
        {{ form_widget(form.direccion, {'attr': {'class': 'form-control', 'placeholder':'direccion'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12">
        <button class="btn btn btn-primary text-white px-4 py-2">{{ button_label|default('Register') }}</button>
    </div>
</div>
{{ form_end(form) }}

templates/usuario/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Usuario{% endblock %}

{% block body %}
    <h1>Edit Usuario</h1>

    {{ include('usuario/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('usuario_index') }}">back to list</a>

    {{ include('usuario/_delete_form.html.twig') }}
{% endblock %}

templates/usuario/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuario index{% endblock %}

{% block body %}
    <h1>Usuario index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Password</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Fecha_alta</th>
                <th>Telefono</th>
                <th>Direccion</th>
                <th>Rol</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.id }}</td>
                <td>{{ usuario.email }}</td>
                <td>{{ usuario.password }}</td>
                <td>{{ usuario.username }}</td>
                <td>{{ usuario.apellidos }}</td>
                <td>{{ usuario.fechaAlta ? usuario.fechaAlta|date('Y-m-d') : '' }}</td>
                <td>{{ usuario.telefono }}</td>
                <td>{{ usuario.direccion }}</td>
                <td>
                    <a href="{{ path('usuario_show', {'id': usuario.id}) }}">show</a>
                    <a href="{{ path('usuario_edit', {'id': usuario.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('usuario_register') }}">Create new</a>
{% endblock %}

templates/usuario/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}New Usuario{% endblock %}

{% block main %}
    <div class="site-wrap">
        <div class="py-5 bg-light">
            <div class="container">
                <div class="row">

                    <div class="col-md-12 col-lg-8 mb-5">
                        <h1>Registro</h1>

                        {{ include('usuario/_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usuario/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuario{% endblock %}

{% block body %}
    <h1>Usuario</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ usuario.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ usuario.email }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ usuario.password }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ usuario.username }}</td>
            </tr>
            <tr>
                <th>Apellidos</th>
                <td>{{ usuario.apellidos }}</td>
            </tr>
            <tr>
                <th>Fecha_alta</th>
                <td>{{ usuario.fechaAlta ? usuario.fechaAlta|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ usuario.telefono }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ usuario.direccion }}</td>
            </tr>
            <tr>
                <th>Rol</th>
                <td>{{ usuario.rol }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('usuario_index') }}">back to list</a>

    <a href="{{ path('usuario_edit', {'id': usuario.id}) }}">edit</a>

    {{ include('usuario/_delete_form.html.twig') }}
{% endblock %}