src/Entity/PlanEntreno.php
<?php

namespace App\Entity;

use App\Repository\PlanEntrenoRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PlanEntrenoRepository::class)
 * @UniqueEntity(fields={"nombre"}, message="El nombre introducido para la rutina ya existe")
 */
class PlanEntreno implements \ArrayAccess
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Por favor, introduce una imagen.")
     * @Assert\File(mimeTypes={ "image/jpeg", "image/png", "image/jpg", "image/gif" })
     * @Assert\Image(
     *     maxWidth = 400,
     *     maxHeight = 400
     * )
     */
    private $imagen;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Introduce un nombre para tu rutina")
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="introduce los cinco ejercicios que la componen")
     */
    private $ejercicio_uno;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="introduce los cinco ejercicios que la componen")
     */
    private $ejercicio_dos;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="introduce los cinco ejercicios que la componen")
     */
    private $ejercicio_tres;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="introduce los cinco ejercicios que la componen")
     */
    private $ejercicio_cuatro;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="introduce los cinco ejercicios que la componen")
     */
    private $ejercicio_cinco;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="describe tu rutina")
     */
    private $descripcion;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $usuarioCreador_id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="indica la especialidad")
     */
    private $tipo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImagen(): ?string
    {
        return $this->imagen;
    }

    public function setImagen(string $imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getEjercicioUno(): ?string
    {
        return $this->ejercicio_uno;
    }

    public function setEjercicioUno(string $ejercicio_uno): self
    {
        $this->ejercicio_uno = $ejercicio_uno;

        return $this;
    }

    public function getEjercicioDos(): ?string
    {
        return $this->ejercicio_dos;
    }

    public function setEjercicioDos(string $ejercicio_dos): self
    {
        $this->ejercicio_dos = $ejercicio_dos;

        return $this;
    }

    public function getEjercicioTres(): ?string
    {
        return $this->ejercicio_tres;
    }

    public function setEjercicioTres(string $ejercicio_tres): self
    {
        $this->ejercicio_tres = $ejercicio_tres;

        return $this;
    }

    public function getEjercicioCuatro(): ?string
    {
        return $this->ejercicio_cuatro;
    }

    public function setEjercicioCuatro(string $ejercicio_cuatro): self
    {
        $this->ejercicio_cuatro = $ejercicio_cuatro;

        return $this;
    }

    public function getEjercicioCinco(): ?string
    {
        return $this->ejercicio_cinco;
    }

    public function setEjercicioCinco(string $ejercicio_cinco): self
    {
        $this->ejercicio_cinco = $ejercicio_cinco;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getUsuarioCreadorId(): ?int
    {
        return $this->usuarioCreador_id;
    }

    public function setUsuarioCreadorId(int $usuarioCreador_id): self
    {
        $this->usuarioCreador_id = $usuarioCreador_id;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function offsetExists($offset)
    {
        // TODO: Implement offsetExists() method.
    }

    public function offsetGet($offset)
    {
        // TODO: Implement offsetGet() method.
    }

    public function offsetSet($offset, $value)
    {
        // TODO: Implement offsetSet() method.
    }

    public function offsetUnset($offset)
    {
        // TODO: Implement offsetUnset() method.
    }
}

src/Form/PlanEntrenoType.php
<?php

namespace App\Form;

use App\Entity\PlanEntreno;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlanEntrenoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        //array('data_class' => null)
        $builder
            ->add('imagen', FileType::class)
            ->add('nombre', TextType::class)
            ->add('ejercicio_uno', TextType::class)
            ->add('ejercicio_dos', TextType::class)
            ->add('ejercicio_tres', TextType::class)
            ->add('ejercicio_cuatro', TextType::class)
            ->add('ejercicio_cinco', TextType::class)
            ->add('descripcion', TextareaType::class)
            ->add('tipo', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PlanEntreno::class,
        ]);
    }
}

src/Controller/PlanEntrenoController.php
<?php

namespace App\Controller;

use App\BLL\PlanEntrenoBLL;
use App\Entity\PlanEntreno;
use App\Form\PlanEntrenoEditType;
use App\Form\PlanEntrenoType;
use App\Repository\PlanEntrenoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/plan_entreno')]
class PlanEntrenoController extends AbstractController
{
    #[Route('/', name: 'plan_entreno_index', methods: ['GET'])]
    public function index(PlanEntrenoRepository $planEntrenoRepository): Response
    {
        return $this->render('plan_entreno/index.html.twig', [
            'plan_entrenos' => $planEntrenoRepository->findAll(),
        ]);
    }

    #[Route('-crear_rutina', name: 'crear_rutina', methods: ['GET', 'POST'])]
    public function new(Request $request, PlanEntrenoBLL $planEntrenoBLL): Response
    {
        $planEntreno = new PlanEntreno();
        $form = $this->createForm(PlanEntrenoType::class, $planEntreno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $planEntrenoBLL->addEntreno($form, $planEntreno);
            return $this->redirectToRoute('perfil_usuario', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('plan_entreno/new.html.twig', [
            'plan_entreno' => $planEntreno,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'plan_entreno_show', methods: ['GET'])]
    public function show(PlanEntreno $planEntreno): Response
    {
        return $this->render('plan_entreno/show.html.twig', [
            'plan_entreno' => $planEntreno,
        ]);
    }

    #[Route('/{id}/edit', name: 'plan_entreno_edit', methods: ['GET', 'POST'])]
    public function edit($id, Request $request, PlanEntreno $planEntreno, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlanEntrenoEditType::class, $planEntreno);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            $img = $form['imagen']->getData();

            $planEntreno->setImagen($img);

            $entityManager->flush();

            return $this->redirectToRoute('detalles_rutina', ['id' => $id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('plan_entreno/edit.html.twig', [
            'plan_entreno' => $planEntreno,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'plan_entreno_delete', methods: ['POST'])]
    public function delete(Request $request, PlanEntreno $planEntreno, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$planEntreno->getId(), $request->request->get('_token'))) {
            $entityManager->remove($planEntreno);
            $entityManager->flush();
        }

        return $this->redirectToRoute('plan_entreno_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/plan_entreno/_delete_form.html.twig
<form method="post" action="{{ path('plan_entreno_delete', {'id': plan_entreno.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ plan_entreno.id) }}">
    <button class="btn">Delete</button>
</form>

templates/plan_entreno/_form.html.twig
{{ form_start(form) }}
{{ form_errors(form) }}
<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="imagen">imagen</label>
        {{ form_widget(form.imagen, {'attr': {'class': 'form-control'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="nombre">nombre</label>
        {{ form_widget(form.nombre, {'attr': {'class': 'form-control', 'placeholder':'nombre de tu rutina'}}) }}
        {{ form_errors(form.nombre) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="ejercicio_uno">nombre 1</label>
        {{ form_widget(form.ejercicio_uno, {'attr': {'class': 'form-control', 'placeholder':'ejercicio uno'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="ejercicio_dos">nombre 2</label>
        {{ form_widget(form.ejercicio_dos, {'attr': {'class': 'form-control', 'placeholder':'ejercicio dos'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="ejercicio_tres">nombre 3</label>
        {{ form_widget(form.ejercicio_tres, {'attr': {'class': 'form-control', 'placeholder':'ejercicio tres'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="ejercicio_cuatro">nombre 4</label>
        {{ form_widget(form.ejercicio_cuatro, {'attr': {'class': 'form-control', 'placeholder':'ejercicio cuatro'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="ejercicio_cinco">nombre 5</label>
        {{ form_widget(form.ejercicio_cinco, {'attr': {'class': 'form-control', 'placeholder':'ejercicio_cinco'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12">
        <label class="font-weight-bold" for="descripcion">Descripcion</label>
        {{ form_widget(form.descripcion, {'attr': {'class': 'form-control', 'cols':'30', 'rows':'5', 'placeholder':'Detalla tu rutina aqui'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 mb-3 mb-md-0">
        <label class="font-weight-bold" for="tipo">Especialidad</label>
        {{ form_widget(form.tipo, {'attr': {'class': 'form-control', 'placeholder':'tipo'}}) }}
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12">
        <button class="btn btn-primary text-white px-4 py-2">{{ button_label|default('Crea') }}</button>
    </div>
</div>
{{ form_end(form) }}

templates/plan_entreno/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Edit PlanEntreno{% endblock %}

{% block main %}
    <div class="py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-8 mb-5">
                    <h1>Edita el plan de entreno</h1>

                    {{ include('plan_entreno/_form.html.twig', {'button_label': 'Update'}) }}

                    <a href="{{ path('rutinas_usuario') }}">Vuelta a mis rutinas</a>

                    {{ include('plan_entreno/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/plan_entreno/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PlanEntreno index{% endblock %}

{% block body %}
    <h1>PlanEntreno index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Imagen</th>
                <th>Nombre</th>
                <th>Ejercicio_uno</th>
                <th>Ejercicio_dos</th>
                <th>Ejercicio_tres</th>
                <th>Ejercicio_cuatro</th>
                <th>Ejercicio_cinco</th>
                <th>Descripcion</th>
                <th>UsuarioCreador_id</th>
                <th>Tipo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for plan_entreno in plan_entrenos %}
            <tr>
                <td>{{ plan_entreno.id }}</td>
                <td>{{ plan_entreno.imagen }}</td>
                <td>{{ plan_entreno.nombre }}</td>
                <td>{{ plan_entreno.ejercicioUno }}</td>
                <td>{{ plan_entreno.ejercicioDos }}</td>
                <td>{{ plan_entreno.ejercicioTres }}</td>
                <td>{{ plan_entreno.ejercicioCuatro }}</td>
                <td>{{ plan_entreno.ejercicioCinco }}</td>
                <td>{{ plan_entreno.descripcion }}</td>
                <td>{{ plan_entreno.usuarioCreadorId }}</td>
                <td>{{ plan_entreno.tipo }}</td>
                <td>
                    <a href="{{ path('plan_entreno_show', {'id': plan_entreno.id}) }}">show</a>
                    <a href="{{ path('plan_entreno_edit', {'id': plan_entreno.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('crear_rutina') }}">Create new</a>
{% endblock %}

templates/plan_entreno/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}New PlanEntreno{% endblock %}

{% block main %}
    <div class="py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-8 mb-5">
                    <h1>Crea tu rutina</h1>

                    {{ include('plan_entreno/_form.html.twig') }}

                    <a href="{{ path('index_page') }}">back to list</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/plan_entreno/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PlanEntreno{% endblock %}

{% block body %}
    <h1>PlanEntreno</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ plan_entreno.id }}</td>
            </tr>
            <tr>
                <th>Imagen</th>
                <td>{{ plan_entreno.imagen }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ plan_entreno.nombre }}</td>
            </tr>
            <tr>
                <th>Ejercicio_uno</th>
                <td>{{ plan_entreno.ejercicioUno }}</td>
            </tr>
            <tr>
                <th>Ejercicio_dos</th>
                <td>{{ plan_entreno.ejercicioDos }}</td>
            </tr>
            <tr>
                <th>Ejercicio_tres</th>
                <td>{{ plan_entreno.ejercicioTres }}</td>
            </tr>
            <tr>
                <th>Ejercicio_cuatro</th>
                <td>{{ plan_entreno.ejercicioCuatro }}</td>
            </tr>
            <tr>
                <th>Ejercicio_cinco</th>
                <td>{{ plan_entreno.ejercicioCinco }}</td>
            </tr>
            <tr>
                <th>Descripcion</th>
                <td>{{ plan_entreno.descripcion }}</td>
            </tr>
            <tr>
                <th>UsuarioCreador_id</th>
                <td>{{ plan_entreno.usuarioCreadorId }}</td>
            </tr>
            <tr>
                <th>Tipo</th>
                <td>{{ plan_entreno.tipo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('plan_entreno_index') }}">back to list</a>

    <a href="{{ path('plan_entreno_edit', {'id': plan_entreno.id}) }}">edit</a>

    {{ include('plan_entreno/_delete_form.html.twig') }}
{% endblock %}