src/Entity/Suscripcion.php
<?php

namespace App\Entity;

use App\Repository\SuscripcionRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SuscripcionRepository::class)
 */
class Suscripcion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_usuario;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_plan_entreno;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_inscripcion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $eleccion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $eleccionNO;

    public function __construct()
    {
        $this->fecha_inscripcion = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUsuario(): ?int
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(int $id_usuario): self
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    public function getIdPlanEntreno(): ?int
    {
        return $this->id_plan_entreno;
    }

    public function setIdPlanEntreno(int $id_plan_entreno): self
    {
        $this->id_plan_entreno = $id_plan_entreno;

        return $this;
    }

    public function getFechaInscripcion(): ?\DateTimeInterface
    {
        return $this->fecha_inscripcion;
    }

    public function setFechaInscripcion(\DateTimeInterface $fecha_inscripcion): self
    {
        $this->fecha_inscripcion = $fecha_inscripcion;

        return $this;
    }

    public function getEleccion(): ?string
    {
        return $this->eleccion;
    }

    public function setEleccion(string $eleccion): self
    {
        $this->eleccion = $eleccion;

        return $this;
    }

    public function getEleccionNO(): ?string
    {
        return $this->eleccionNO;
    }

    public function setEleccionNO(?string $eleccionNO): self
    {
        $this->eleccionNO = $eleccionNO;

        return $this;
    }
}

src/Form/SuscripcionType.php
<?php

namespace App\Form;

use App\Entity\Suscripcion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SuscripcionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('eleccion', RadioType::class)
            ->add('eleccionNO', RadioType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Suscripcion::class,
        ]);
    }
}

src/Controller/SuscripcionController.php
<?php

namespace App\Controller;

use App\Entity\Suscripcion;
use App\Form\SuscripcionType;
use App\Repository\SuscripcionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/suscripcion')]
class SuscripcionController extends AbstractController
{
    #[Route('/', name: 'suscripcion_index', methods: ['GET'])]
    public function index(SuscripcionRepository $suscripcionRepository): Response
    {
        return $this->render('suscripcion/index.html.twig', [
            'suscripcions' => $suscripcionRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'suscripcion_show', methods: ['GET'])]
    public function show(Suscripcion $suscripcion): Response
    {
        return $this->render('suscripcion/show.html.twig', [
            'suscripcion' => $suscripcion,
        ]);
    }

    #[Route('/{id}/edit', name: 'suscripcion_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Suscripcion $suscripcion, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SuscripcionType::class, $suscripcion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('suscripcion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('suscripcion/edit.html.twig', [
            'suscripcion' => $suscripcion,
            'form' => $form,
        ]);
    }

    #[Route('/suscribete/{id}', name: 'suscribete', methods: ['GET', 'POST'])]
    public function new($id, Request $request, EntityManagerInterface $entityManager, SuscripcionRepository $sus): Response
    {
        $suscripcion = new Suscripcion();

        $user = $this->getUser();
        $id_user = $user->getId();

        $suscripcion->setIdUsuario($id_user);
        $suscripcion->setIdPlanEntreno($id);

        $existe = $sus->findOneBy([
            'id_usuario' => $id_user,
            'id_plan_entreno' => $id
        ]);

        if(is_null($existe)){
            $entityManager->persist($suscripcion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('detalles_rutina', ['id' => $id], Response::HTTP_SEE_OTHER);
    }

    #[Route('/unsuscribete/{id}', name: 'unsub', methods: ['GET', 'POST'])]
    public function unsuscribete($id, Request $request, EntityManagerInterface $entityManager, SuscripcionRepository $sus) : Response
    {
        $user = $this->getUser();
        $id_user = $user->getId();

        $suscripcion = $sus->findOneBy([
            'id_usuario' => $id_user,
            'id_plan_entreno' => $id
        ]);

        $entityManager->remove($suscripcion);
        $entityManager->flush();

        return $this->redirectToRoute('detalles_rutina', ['id' => $id], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'suscripcion_delete', methods: ['POST'])]
    public function delete(Request $request, Suscripcion $suscripcion, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$suscripcion->getId(), $request->request->get('_token'))) {
            $entityManager->remove($suscripcion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('suscripcion_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/suscripcion/_delete_form.html.twig
<form method="post" action="{{ path('suscripcion_delete', {'id': suscripcion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ suscripcion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/suscripcion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Suscripcion{% endblock %}

{% block body %}
    <h1>Edit Suscripcion</h1>

    {{ include('suscripcion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('suscripcion_index') }}">back to list</a>

    {{ include('suscripcion/_delete_form.html.twig') }}
{% endblock %}

templates/suscripcion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Suscripcion index{% endblock %}

{% block body %}
    <h1>Suscripcion index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_usuario</th>
                <th>Id_plan_entreno</th>
                <th>Fecha_inscripcion</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for suscripcion in suscripcions %}
            <tr>
                <td>{{ suscripcion.id }}</td>
                <td>{{ suscripcion.idUsuario }}</td>
                <td>{{ suscripcion.idPlanEntreno }}</td>
                <td>{{ suscripcion.fechaInscripcion ? suscripcion.fechaInscripcion|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('suscripcion_show', {'id': suscripcion.id}) }}">show</a>
                    <a href="{{ path('suscripcion_edit', {'id': suscripcion.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('suscripcion') }}">Create new</a>
{% endblock %}

templates/suscripcion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Suscripcion{% endblock %}

{% block body %}
    <h1>Suscripcion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ suscripcion.id }}</td>
            </tr>
            <tr>
                <th>Id_usuario</th>
                <td>{{ suscripcion.idUsuario }}</td>
            </tr>
            <tr>
                <th>Id_plan_entreno</th>
                <td>{{ suscripcion.idPlanEntreno }}</td>
            </tr>
            <tr>
                <th>Fecha_inscripcion</th>
                <td>{{ suscripcion.fechaInscripcion ? suscripcion.fechaInscripcion|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('suscripcion_index') }}">back to list</a>

    <a href="{{ path('suscripcion_edit', {'id': suscripcion.id}) }}">edit</a>

    {{ include('suscripcion/_delete_form.html.twig') }}
{% endblock %}

templates/suscripcion/suscripcion.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    {{ form_start(form) }}
        <div class="col-md-12">
            <label class="font-weight-bold" for="suscripcion">Usuario: {{ app.user.username }}<!-- <?php echo 'Usuario logueado: ' . $user ?> --> </label>
        </div>
        <div style="margin-left: 15px">
            <p>Desea suscribirse a la rutina?</p>
            <label for="si">Si</label>
            {{ form_widget(form.eleccion, {'attr': {'name':'suscripcion', 'class': 'btn btn-primary text-white px-4 py-2', 'style':'margin-left: 15px;', 'placeholder':'comenta...', 'value':'si'}}) }}

            <label for="no">No</label>
            {{ form_widget(form.eleccionNO, {'attr': {'name':'suscripcion', 'class': 'btn btn-primary text-white px-4 py-2', 'style':'margin-left: 15px;', 'placeholder':'comenta...', 'value':'no'}}) }}

        </div>
        <div class="row form-group">
            <div class="col-md-12">
                <button class="btn btn-primary text-white px-4 py-2">{{ button_label|default('Suscribeme!') }}</button>
            </div>
        </div>
    {{ form_end(form) }}
{% endblock %}

templates/suscripcion/unsuscripcion.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    {{ form_start(form) }}
    <div class="col-md-12">
        <label class="font-weight-bold" for="suscripcion">Nombre del usuario logueado aqui. <!-- <?php echo 'Usuario logueado: ' . $user ?> --> </label>
    </div>
    <div style="margin-left: 15px">
        <p>Desea eliminar su suscripcion a la rutina?</p>
        <label for="si">Si</label>
        {{ form_widget(form.eleccion, {'attr': {'name':'suscripcion', 'class': 'btn btn-primary text-white px-4 py-2', 'style':'margin-left: 15px;', 'placeholder':'comenta...', 'value':'si'}}) }}

        <label for="no">No</label>
        {{ form_widget(form.eleccionNO, {'attr': {'name':'suscripcion', 'class': 'btn btn-primary text-white px-4 py-2', 'style':'margin-left: 15px;', 'placeholder':'comenta...', 'value':'no'}}) }}
    </div>
    <div class="row form-group">
        <div class="col-md-12">
            <button class="btn btn-primary text-white px-4 py-2">{{ button_label|default('Suscribeme!') }}</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}