src/Entity/Comentario.php
<?php

namespace App\Entity;

use App\Repository\ComentarioRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ComentarioRepository::class)
 */
class Comentario
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $usuario_id;

    /**
     * @ORM\Column(type="text")
     */
    private $texto;

    /**
     * @ORM\Column(type="integer")
     */
    private $rutina_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function __construct()
    {
        $this->date = new DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsuarioId(): ?int
    {
        return $this->usuario_id;
    }

    public function setUsuarioId(int $usuario_id): self
    {
        $this->usuario_id = $usuario_id;

        return $this;
    }

    public function getTexto(): ?string
    {
        return $this->texto;
    }

    public function setTexto(string $texto): self
    {
        $this->texto = $texto;

        return $this;
    }

    public function getRutinaId(): ?int
    {
        return $this->rutina_id;
    }

    public function setRutinaId(int $rutina_id): self
    {
        $this->rutina_id = $rutina_id;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Form/ComentarioType.php
<?php

namespace App\Form;

use App\Entity\Comentario;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ComentarioType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('texto', TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comentario::class,
        ]);
    }
}

src/Controller/ComentarioController.php
<?php

namespace App\Controller;

use App\Entity\Comentario;
use App\Form\ComentarioType;
use App\Repository\ComentarioRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/comentario')]
class ComentarioController extends AbstractController
{
    #[Route('/', name: 'comentario_index', methods: ['GET'])]
    public function index(ComentarioRepository $comentarioRepository): Response
    {
        return $this->render('comentario/index.html.twig', [
            'comentarios' => $comentarioRepository->findAll(),
        ]);
    }

    #[Route('/nuevo_comentario/{id}', name: 'comentario_page', methods: ['GET', 'POST'])]
    public function new($id, Request $request, EntityManagerInterface $entityManager): Response
    {
        $comentario = new Comentario();
        $form = $this->createForm(ComentarioType::class, $comentario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //Id del usuario que comenta
            $user = $this->getUser();
            $id_user = $user->getId();

            $comentario->setUsuarioId($id_user);
            $comentario->setRutinaId($id);

            $entityManager->persist($comentario);
            $entityManager->flush();

            return $this->redirectToRoute('detalles_rutina', ['id' => $id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('comentario/new.html.twig', [
            'comentario' => $comentario,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'comentario_show', methods: ['GET'])]
    public function show(Comentario $comentario): Response
    {
        return $this->render('comentario/show.html.twig', [
            'comentario' => $comentario,
        ]);
    }

    #[Route('/{id}/edit', name: 'comentario_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comentario $comentario, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ComentarioType::class, $comentario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('comentario_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('comentario/edit.html.twig', [
            'comentario' => $comentario,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'comentario_delete', methods: ['POST'])]
    public function delete(Request $request, Comentario $comentario, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comentario->getId(), $request->request->get('_token'))) {
            $entityManager->remove($comentario);
            $entityManager->flush();
        }

        return $this->redirectToRoute('comentario_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/comentario/_delete_form.html.twig
<form method="post" action="{{ path('comentario_delete', {'id': comentario.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comentario.id) }}">
    <button class="btn">Delete</button>
</form>

templates/comentario/_form.html.twig
{{ form_start(form) }}
    <div>
        <div class="col-md-12">
            <label class="font-weight-bold" for="comentario"></label>
            {{ form_widget(form.texto, {'attr': {'class': 'form-control', 'placeholder':'comenta...', 'cols':'30', 'rows':'5'}}) }}
        </div>
        <button class="btn btn-primary text-white px-4 py-2" style="margin-left: 15px;">{{ button_label|default('comenta') }}</button>
    </div>
{{ form_end(form) }}

templates/comentario/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comentario{% endblock %}

{% block body %}
    <h1>Edit Comentario</h1>

    {{ include('comentario/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('comentario_index') }}">back to list</a>

    {{ include('comentario/_delete_form.html.twig') }}
{% endblock %}

templates/comentario/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comentario index{% endblock %}

{% block body %}
    <h1>Comentario index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Usuario_id</th>
                <th>Texto</th>
                <th>Rutina_id</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for comentario in comentarios %}
            <tr>
                <td>{{ comentario.id }}</td>
                <td>{{ comentario.usuarioId }}</td>
                <td>{{ comentario.texto }}</td>
                <td>{{ comentario.rutinaId }}</td>
                <td>{{ comentario.date ? comentario.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('comentario_show', {'id': comentario.id}) }}">show</a>
                    <a href="{{ path('comentario_edit', {'id': comentario.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('comentario_page') }}">Create new</a>
{% endblock %}

templates/comentario/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}New Comentario{% endblock %}

{% block main %}
    <h1>Comenta!</h1>

    {{ include('comentario/_form.html.twig') }}
{% endblock %}

templates/comentario/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comentario{% endblock %}

{% block body %}
    <h1>Comentario</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ comentario.id }}</td>
            </tr>
            <tr>
                <th>Usuario_id</th>
                <td>{{ comentario.usuarioId }}</td>
            </tr>
            <tr>
                <th>Texto</th>
                <td>{{ comentario.texto }}</td>
            </tr>
            <tr>
                <th>Rutina_id</th>
                <td>{{ comentario.rutinaId }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ comentario.date ? comentario.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('comentario_index') }}">back to list</a>

    <a href="{{ path('comentario_edit', {'id': comentario.id}) }}">edit</a>

    {{ include('comentario/_delete_form.html.twig') }}
{% endblock %}